[package]
name = "mkbookpdf"
version = "0.1.0"
authors = ["coord.e <me@coord-e.com>"]
edition = "2018"

[dependencies]
lopdf = "0.23.0"
structopt = "0.3"
tempfile = "3.1.0"

[dev-dependencies]
assert_cmd = "0.11"
assert_fs = "0.11"
predicates = "1.0.1"