on:
  push:
    tags: ['*']

name: Release

jobs:
  upload:
    name: Upload to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            rust_flags: ''
          - os: macOS-latest
            target: x86_64-apple-darwin
            rust_flags: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            rust_flags: -C target-feature=+crt-static
    env:
      RUSTFLAGS: ${{ matrix.rust_flags }}
      MACOSX_DEPLOYMENT_TARGET: 10.7
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target=${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features --target=${{ matrix.target }}
      - run: mv target/${{ matrix.target }}/release/mkbookpdf mkbookpdf-${{ matrix.target }}
        if: matrix.os != 'windows-latest'
      - run: move target\${{ matrix.target }}\release\mkbookpdf.exe mkbookpdf-${{ matrix.target }}.exe
        if: matrix.os == 'windows-latest'
      - uses: softprops/action-gh-release@v1
        with:
          files: mkbookpdf-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
